version: '3.8'

networks:
  snb_net:
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.1 # Replace with your actual network gateway

services:
  dns:
    build:
      context: .
      dockerfile: dns/Dockerfile
    networks:
      snb_net:
        ipv4_address: 192.168.3.12
    environment:
      - TEAM_IP=192.168.3.12
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"

  bastion:
    build:
      context: .
      dockerfile: bastion/Dockerfile
    networks:
      snb_net:
        ipv4_address: 192.168.3.10
    restart: unless-stopped

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    networks:
      snb_net:
        ipv4_address: 192.168.3.7
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: national_bank
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d national_bank"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      snb_net:
        ipv4_address: 192.168.3.6
    environment:
      - DATABASE_URL=postgresql://user:password@192.168.3.7:5432/national_bank
      - FRONTEND_URL=https://192.168.3.5
      - JWT_SECRET=5d7845ac6ee7cfffafc5fe5f35cf666d
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    networks:
      snb_net:
        ipv4_address: 192.168.3.11
    environment:
      - NEXT_PUBLIC_API_URL=https://192.168.3.5/api
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
    networks:
      snb_net:
        ipv4_address: 192.168.3.5
    environment:
      - CERT_DOMAIN=ca.ncaecybergames.org
      - CERT_EMAIL=admin@ca.ncaecybergames.org
    depends_on:
      - frontend
      - backend

volumes:
  pgdata: